# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_Contatos.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Contatos(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 530)
        MainWindow.setMinimumSize(QtCore.QSize(300, 530))
        MainWindow.setMaximumSize(QtCore.QSize(300, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tela_perfil = QtWidgets.QFrame(self.centralwidget)
        self.tela_perfil.setStyleSheet("background-color: rgb(170, 232, 185);\n"
"")
        self.tela_perfil.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_perfil.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_perfil.setObjectName("tela_perfil")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tela_perfil)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_cima = QtWidgets.QFrame(self.tela_perfil)
        self.frame_cima.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_cima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_cima.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_cima.setObjectName("frame_cima")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_cima)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_busca = QtWidgets.QFrame(self.frame_cima)
        self.frame_busca.setMaximumSize(QtCore.QSize(210, 16777215))
        self.frame_busca.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_busca.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_busca.setObjectName("frame_busca")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_busca)
        self.verticalLayout_3.setContentsMargins(6, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.caixa_busca = QtWidgets.QTextEdit(self.frame_busca)
        self.caixa_busca.setObjectName("caixa_busca")
        self.verticalLayout_3.addWidget(self.caixa_busca)
        self.horizontalLayout_2.addWidget(self.frame_busca)
        self.botao_buscar = QtWidgets.QPushButton(self.frame_cima)
        self.botao_buscar.setMinimumSize(QtCore.QSize(0, 30))
        self.botao_buscar.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 255, 0);\n"
"}\n"
"")
        self.botao_buscar.setObjectName("botao_buscar")
        self.horizontalLayout_2.addWidget(self.botao_buscar)
        self.verticalLayout_2.addWidget(self.frame_cima)
        self.tela_perfil_meio = QtWidgets.QFrame(self.tela_perfil)
        self.tela_perfil_meio.setMinimumSize(QtCore.QSize(0, 300))
        self.tela_perfil_meio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_perfil_meio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_perfil_meio.setObjectName("tela_perfil_meio")
        self.gridLayout = QtWidgets.QGridLayout(self.tela_perfil_meio)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_m = QtWidgets.QFrame(self.tela_perfil_meio)
        self.frame_m.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_m.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_m.setObjectName("frame_m")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_m)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.area_contatos = QtWidgets.QTextBrowser(self.frame_m)
        self.area_contatos.setObjectName("area_contatos")
        self.verticalLayout_4.addWidget(self.area_contatos)
        self.gridLayout.addWidget(self.frame_m, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.tela_perfil_meio)
        self.tela_perfil_baixo = QtWidgets.QFrame(self.tela_perfil)
        self.tela_perfil_baixo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tela_perfil_baixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_perfil_baixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_perfil_baixo.setObjectName("tela_perfil_baixo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tela_perfil_baixo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botao_conversas = QtWidgets.QPushButton(self.tela_perfil_baixo)
        self.botao_conversas.setMaximumSize(QtCore.QSize(150, 16777215))
        self.botao_conversas.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 255, 0);\n"
"}\n"
"")
        self.botao_conversas.setObjectName("botao_conversas")
        self.horizontalLayout.addWidget(self.botao_conversas)
        self.botao_inicio = QtWidgets.QPushButton(self.tela_perfil_baixo)
        self.botao_inicio.setMaximumSize(QtCore.QSize(150, 16777215))
        self.botao_inicio.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 255, 0);\n"
"}\n"
"")
        self.botao_inicio.setObjectName("botao_inicio")
        self.horizontalLayout.addWidget(self.botao_inicio)
        self.botao_sair = QtWidgets.QPushButton(self.tela_perfil_baixo)
        self.botao_sair.setMaximumSize(QtCore.QSize(150, 16777215))
        self.botao_sair.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 255, 0);\n"
"}\n"
"")
        self.botao_sair.setObjectName("botao_sair")
        self.horizontalLayout.addWidget(self.botao_sair)
        self.verticalLayout_2.addWidget(self.tela_perfil_baixo)
        self.verticalLayout.addWidget(self.tela_perfil)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botao_buscar.setText(_translate("MainWindow", "Buscar"))
        self.botao_conversas.setText(_translate("MainWindow", "Conversas"))
        self.botao_inicio.setText(_translate("MainWindow", "Inicio"))
        self.botao_sair.setText(_translate("MainWindow", "Perfil"))
# import icones_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Contatos()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
