# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_Cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Cadastro(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 530)
        MainWindow.setMinimumSize(QtCore.QSize(300, 530))
        MainWindow.setMaximumSize(QtCore.QSize(300, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tela_login = QtWidgets.QFrame(self.centralwidget)
        self.tela_login.setStyleSheet("background-color: rgb(170, 232, 185);\n"
"")
        self.tela_login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_login.setObjectName("tela_login")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tela_login)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tela_login_cima = QtWidgets.QFrame(self.tela_login)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tela_login_cima.sizePolicy().hasHeightForWidth())
        self.tela_login_cima.setSizePolicy(sizePolicy)
        self.tela_login_cima.setStyleSheet("background-image: url(:/icones/logo_full_mini.png);\n"
"background-repeat: norepeat; \n"
"background-position: center")
        self.tela_login_cima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_login_cima.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_login_cima.setObjectName("tela_login_cima")
        self.verticalLayout_2.addWidget(self.tela_login_cima)
        self.tela_login_meio = QtWidgets.QFrame(self.tela_login)
        self.tela_login_meio.setMinimumSize(QtCore.QSize(0, 300))
        self.tela_login_meio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_login_meio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_login_meio.setObjectName("tela_login_meio")
        self.gridLayout = QtWidgets.QGridLayout(self.tela_login_meio)
        self.gridLayout.setObjectName("gridLayout")
        self.botao_ir_cadastro = QtWidgets.QPushButton(self.tela_login_meio)
        self.botao_ir_cadastro.setMaximumSize(QtCore.QSize(300, 16777215))
        self.botao_ir_cadastro.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 255, 0);\n"
"}\n"
"")
        self.botao_ir_cadastro.setObjectName("botao_ir_cadastro")
        self.gridLayout.addWidget(self.botao_ir_cadastro, 4, 0, 1, 2)
        self.caixa_senha = QtWidgets.QLineEdit(self.tela_login_meio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caixa_senha.sizePolicy().hasHeightForWidth())
        self.caixa_senha.setSizePolicy(sizePolicy)
        self.caixa_senha.setMaximumSize(QtCore.QSize(300, 16777215))
        self.caixa_senha.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 15px;\n"
"    background-color: rgb(151, 206, 164);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 4px solid rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QLineEdit:focus {\n"
"    border: 4px solid rgb(0, 0, 0);\n"
"    color :rgb(0,0,0)\n"
"}\n"
"")
        self.caixa_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.caixa_senha.setObjectName("caixa_senha")
        self.gridLayout.addWidget(self.caixa_senha, 3, 0, 1, 2)
        self.caixa_usuario = QtWidgets.QLineEdit(self.tela_login_meio)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.caixa_usuario.sizePolicy().hasHeightForWidth())
        self.caixa_usuario.setSizePolicy(sizePolicy)
        self.caixa_usuario.setMaximumSize(QtCore.QSize(300, 16777215))
        self.caixa_usuario.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 15px;\n"
"    background-color: rgb(151, 206, 164);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 4px solid rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QLineEdit:focus {\n"
"    border: 4px solid rgb(0, 0, 0);\n"
"    color :rgb(0,0,0)\n"
"}\n"
"")
        self.caixa_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.caixa_usuario.setObjectName("caixa_usuario")
        self.gridLayout.addWidget(self.caixa_usuario, 2, 0, 1, 2)
        self.caixa_email = QtWidgets.QLineEdit(self.tela_login_meio)
        self.caixa_email.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 15px;\n"
"    background-color: rgb(151, 206, 164);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 4px solid rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QLineEdit:focus {\n"
"    border: 4px solid rgb(0, 0, 0);\n"
"    color :rgb(0,0,0)\n"
"}\n"
"")
        self.caixa_email.setAlignment(QtCore.Qt.AlignCenter)
        self.caixa_email.setObjectName("caixa_email")
        self.gridLayout.addWidget(self.caixa_email, 1, 0, 1, 2)
        self.caixa_nome = QtWidgets.QLineEdit(self.tela_login_meio)
        self.caixa_nome.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 15px;\n"
"    background-color: rgb(151, 206, 164);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 4px solid rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QLineEdit:focus {\n"
"    border: 4px solid rgb(0, 0, 0);\n"
"    color :rgb(0,0,0)\n"
"}\n"
"")
        self.caixa_nome.setAlignment(QtCore.Qt.AlignCenter)
        self.caixa_nome.setObjectName("caixa_nome")
        self.gridLayout.addWidget(self.caixa_nome, 0, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.tela_login_meio)
        self.tela_login_baixo = QtWidgets.QFrame(self.tela_login)
        self.tela_login_baixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_login_baixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_login_baixo.setObjectName("tela_login_baixo")
        self.botao_sair = QtWidgets.QPushButton(self.tela_login_baixo)
        self.botao_sair.setGeometry(QtCore.QRect(0, 70, 91, 30))
        self.botao_sair.setMaximumSize(QtCore.QSize(150, 16777215))
        self.botao_sair.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 255, 0);\n"
"}\n"
"")
        self.botao_sair.setObjectName("botao_sair")
        self.verticalLayout_2.addWidget(self.tela_login_baixo)
        self.verticalLayout.addWidget(self.tela_login)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botao_ir_cadastro.setText(_translate("MainWindow", "Cadastrar"))
        self.caixa_senha.setPlaceholderText(_translate("MainWindow", "SENHA"))
        self.caixa_usuario.setPlaceholderText(_translate("MainWindow", "USUÁRIO"))
        self.caixa_email.setPlaceholderText(_translate("MainWindow", "EMAIL"))
        self.caixa_nome.setPlaceholderText(_translate("MainWindow", "NOME"))
        self.botao_sair.setText(_translate("MainWindow", "Voltar"))
#import icones_rc
