# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teste.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_Principal(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 530)
        MainWindow.setMinimumSize(QtCore.QSize(300, 530))
        MainWindow.setMaximumSize(QtCore.QSize(300, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tela_principal = QtWidgets.QFrame(self.centralwidget)
        self.tela_principal.setStyleSheet("background-color: rgb(170, 232, 185);\n"
"")
        self.tela_principal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_principal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_principal.setObjectName("tela_principal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tela_principal)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.principal_cima = QtWidgets.QFrame(self.tela_principal)
        self.principal_cima.setMaximumSize(QtCore.QSize(16777215, 80))
        self.principal_cima.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.principal_cima.setFrameShadow(QtWidgets.QFrame.Raised)
        self.principal_cima.setObjectName("principal_cima")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.principal_cima)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.foto_perfil = QtWidgets.QFrame(self.principal_cima)
        self.foto_perfil.setMinimumSize(QtCore.QSize(60, 0))
        self.foto_perfil.setMaximumSize(QtCore.QSize(60, 16777215))
        self.foto_perfil.setStyleSheet("QFrame{\n"
"    \n"
"    image: url(:/icones/pato.jpg);\n"
"    \n"
"    border-radius : 100px;\n"
"    border: 3px solid rgb(54, 255, 32)\n"
"}")
        self.foto_perfil.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foto_perfil.setFrameShadow(QtWidgets.QFrame.Plain)
        self.foto_perfil.setObjectName("foto_perfil")
        self.horizontalLayout_2.addWidget(self.foto_perfil)
        self.texto_postar = QtWidgets.QTextEdit(self.principal_cima)
        self.texto_postar.setStyleSheet("QTextEdit{\n"
"    border: 1px solid rgb(54, 255, 32);\n"
"    font: 63 8pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"QTextEdit:hover{\n"
"    border: 3px solid rgb(54, 255, 32);\n"
"}\n"
"QTextEdit:focus{\n"
"    border: 3px solid rgb(54, 255, 32);\n"
"    \n"
"    background-color: rgb(183, 249, 198);\n"
"    color: rgb(0, 0, 0)\n"
"}")
        self.texto_postar.setObjectName("texto_postar")
        self.horizontalLayout_2.addWidget(self.texto_postar)
        self.botao_postar = QtWidgets.QPushButton(self.principal_cima)
        self.botao_postar.setMinimumSize(QtCore.QSize(0, 60))
        self.botao_postar.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 255, 0);\n"
"}\n"
"")
        self.botao_postar.setObjectName("botao_postar")
        self.horizontalLayout_2.addWidget(self.botao_postar)
        self.verticalLayout_2.addWidget(self.principal_cima)
        self.tela_principal_meio = QtWidgets.QFrame(self.tela_principal)
        self.tela_principal_meio.setMinimumSize(QtCore.QSize(0, 300))
        self.tela_principal_meio.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_principal_meio.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_principal_meio.setObjectName("tela_principal_meio")
        self.gridLayout = QtWidgets.QGridLayout(self.tela_principal_meio)
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.area_rolagem = QtWidgets.QScrollArea(self.tela_principal_meio)
        self.area_rolagem.setWidgetResizable(True)
        self.area_rolagem.setObjectName("area_rolagem")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 285, 376))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_mensagens = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_mensagens.setGeometry(QtCore.QRect(20, 20, 47, 13))
        self.label_mensagens.setObjectName("label_mensagens")
        self.textEdit_mensagens = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit_mensagens.setGeometry(QtCore.QRect(10, 50, 104, 71))
        self.textEdit_mensagens.setObjectName("textEdit_mensagens")
        self.area_rolagem.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.area_rolagem, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.tela_principal_meio)
        self.tela_principal_baixo = QtWidgets.QFrame(self.tela_principal)
        self.tela_principal_baixo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.tela_principal_baixo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tela_principal_baixo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tela_principal_baixo.setObjectName("tela_principal_baixo")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tela_principal_baixo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.botao_conversas = QtWidgets.QPushButton(self.tela_principal_baixo)
        self.botao_conversas.setMaximumSize(QtCore.QSize(150, 16777215))
        self.botao_conversas.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 255, 0);\n"
"}\n"
"")
        self.botao_conversas.setObjectName("botao_conversas")
        self.horizontalLayout.addWidget(self.botao_conversas)
        self.botao_inicio = QtWidgets.QPushButton(self.tela_principal_baixo)
        self.botao_inicio.setMaximumSize(QtCore.QSize(150, 16777215))
        self.botao_inicio.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 255, 0);\n"
"}\n"
"")
        self.botao_inicio.setObjectName("botao_inicio")
        self.horizontalLayout.addWidget(self.botao_inicio)
        self.botao_perfil = QtWidgets.QPushButton(self.tela_principal_baixo)
        self.botao_perfil.setMaximumSize(QtCore.QSize(150, 16777215))
        self.botao_perfil.setStyleSheet("QPushButton {\n"
"    border: 3px solid rgb(146, 232, 141);\n"
"    border-radius: 4px;\n"
"    padding: 1px;\n"
"    background-color:  rgb(146, 232, 141);\n"
"    color: rgb(0,0,0);\n"
"    \n"
"    font: 87 11pt \"Arial Black\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:  rgb(95, 232, 71);\n"
"    \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(12, 255, 0);\n"
"}\n"
"")
        self.botao_perfil.setObjectName("botao_perfil")
        self.horizontalLayout.addWidget(self.botao_perfil)
        self.verticalLayout_2.addWidget(self.tela_principal_baixo)
        self.verticalLayout.addWidget(self.tela_principal)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.texto_postar.setPlaceholderText(_translate("MainWindow", "Compartilhe algo..."))
        self.botao_postar.setText(_translate("MainWindow", "Postar"))
        self.label_mensagens.setText(_translate("MainWindow", "TextLabel"))
        self.botao_conversas.setText(_translate("MainWindow", "Conversas"))
        self.botao_inicio.setText(_translate("MainWindow", "Inicio"))
        self.botao_perfil.setText(_translate("MainWindow", "Perfil"))
# import icones_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_Principal()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
